package com.agnext.zohodatasync.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Subselect;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Immutable
@Getter
@Setter
@ToString
@Table(name = "dbo.Mx_VEW_APIDailyAttendance")
public class AttendanceViewEntity {

	@Id
	private Long id;
	@Column(name = "UserID")
	private String userId;
	private String UserName;
	private String Short_Name;
	private String INTEGRATION_REFERENCE;
	private String ORGID;
	private String BRCID;
	private String DPTID;
	private String SECID;
	private String CTGID;
	private String GRDID;
	private String DSGID;
	private String CustomGroup1ID;
	private String CustomGroup2ID;
	private String CustomGroup3ID;
	private String AdlUserID;
	private String Gender;
	private String MRTLSTAT;
	private String BirthDT;
	private String JoinDT;
	private String LeaveDT;
	private String ProcessDate;
	private String ProcessDate_D;
	private String Punch1;
	private String Punch1_Date;
	private String Punch1_Time;
	private String Punch2;
	private String Punch2_Date;
	private String Punch2_Time;
	private String Punch3;
	private String Punch3_Date;
	private String Punch3_Time;
	private String Punch4;
	private String Punch4_Date;
	private String Punch4_Time;
	private String Punch5;
	private String Punch5_Date;
	private String Punch5_Time;
	private String Punch6;
	private String Punch6_Date;
	private String Punch6_Time;
	private String Punch7;
	private String Punch7_Date;
	private String Punch7_Time;
	private String Punch8;
	private String Punch8_Date;
	private String Punch8_Time;
	private String Punch9;
	private String Punch9_Date;
	private String Punch9_Time;
	private String Punch10;
	private String Punch10_Date;
	private String Punch10_Time;
	private String Punch11;
	private String Punch11_Date;
	private String Punch11_Time;
	private String Punch12;
	private String Punch12_Date;
	private String Punch12_Time;
	private String SPFID1;
	private String SPFID2;
	private String SPFID3;
	private String SPFID4;
	private String SPFID5;
	private String SPFID6;
	private String SPFID7;
	private String SPFID8;
	private String SPFID9;
	private String SPFID10;
	private String SPFID11;
	private String SPFID12;
	private String ScheduleShift;
	private String WorkingShift;
	private String EarlyIn;
	private String EarlyIn_HHMM;
	private String LateIn;
	private String LateIn_HHMM;
	private String EarlyOut;
	private String EarlyOut_HHMM;
	private String Overstay;
	private String Overstay_HHMM;
	private String Overtime;
	private String Overtime_HHMM;
	private String WorkTime;
	private String WorkTime_HHMM;
	private String FirstHalf;
	private String SecondHalf;
	private String ManualOvertime_Credit;
	private String ManualOvertime_Credit_HHMM;
	private String ManualOvertime_Debit;
	private String ManualOvertime_Debit_HHMM;
	private String AuthorizedOvertime;
	private String AuthorizedOvertime_HHMM;
	private String OvertimeAuthorizationDate;
	private String ManualCOFF_Credit;
	private String ManualCOFF_Credit_HHMM;
	private String ManualCOFF_Debit;
	private String ManualCOFF_Debit_HHMM;
	private String AuthorizedCOFF;
	private String AuthorizedCOFF_HHMM;
	private String AuthorizedCOFFDate;
	private String AvailedCOFF;
	private String AvailedCOFF_HHMM;
	private String EncashedCOFF;
	private String EncashedCOFF_HHMM;
	private String LunchDuration;
	private String LunchDuration_HHMM;
	private String LateInLunch;
	private String LateInLunch_HHMM;
	private String EarlyOutLunch;
	private String EarlyOutLunch_HHMM;
	private String WeekOFFANDHoliday;
	private String OfficialDuration;
	private String PersonalDuration;
	private String ShiftStart;
	private String ShiftEnd;
	private String LunchStart;
	private String LunchEnd;
	private String OutPunch;
	private String OutPunch_Date;
	private String OutPunch_Time;
	private String OutSPFID;
	private String SiteID;
	private String MinWrkHrsFDay;
	private String MinWrkHrsFDay_HHMM;
	private String MinWrkHrsHDay;
	private String MinWrkHrsHDay_HHMM;
	private String ShiftType;
	private String DAYSTATUS;
	private String NETWORKHRS;
	private String ADJUSTEDHRS;
	private String SUMMARY;
	private String punch_reason1;
	private String punch_reason2;
	private String punch_reason3;
	private String punch_reason4;
	private String punch_reason5;
	private String punch_reason6;
	private String punch_reason7;
	private String punch_reason8;
	private String punch_reason9;
	private String punch_reason10;
	private String punch_reason11;
	private String punch_reason12;
	private String OVERTIME1;
	private String OVERTIME2;
	private String OVERTIME3;
	private String OVERTIME4;
	private String OVERTIME5;
	private String AUTHOT1;
	private String AUTHOT2;
	private String AUTHOT3;
	private String AUTHOT4;
	private String AUTHOT5;
	private String Field1;
	private String Field2;
	private String Field3;
	private String Field4;
	private String Field5;
	private String Field6;
	private String Field7;
	private String Field8;
	private String Field9;
	private String Field10;
	private String short_leave_count;
	private String short_leave_hours;
	private String official_hours;
	private String organization_name;
	private String branch_name;
	private String designation_name;
	private String section_name;
	private String department_name;
	private String category_name;
	private String grade_name;
	private String CustomGroup1_Name;
	private String CustomGroup2_Name;
	private String CustomGroup3_Name;
	private String UserType;
	private String ActiveFlag;
	private String FullName;
	private String AVAILEDPLHours;
	private String AVAILEDULHours;



}
